# Generated by Django 6.0.4 on 2026-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_category_description'),
        ('sanskriti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageitem',
            name='community_tags',
            field=models.ManyToManyField(blank=True, help_text='Tag which religions, castes, or subcastes this heritage item belongs to.', related_name='heritage_items', to='sanskriti.ethnicityprofile'),
        ),
    ]
