# Generated by Django 6.0.4 on 2026-04-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='addwd_at',
            new_name='added_at',
        ),
    ]
