# Generated by Django 6.0.4 on 2026-05-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_addwd_at_contribution_added_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
