# Generated by Django 6.0.4 on 2026-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
