# Generated by Django 6.0.4 on 2026-05-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_remove_contribution_is_verified_contribution_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='vedio',
            new_name='video',
        ),
    ]
