# Generated by Django 6.0.4 on 2026-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_rename_vedio_contribution_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='description',
            field=models.TextField(verbose_name=1000),
        ),
    ]
