# Generated by Django 6.0.4 on 2026-05-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthnicityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('node_type', models.CharField(choices=[('religion', 'Religion'), ('caste', 'Caste/Ethnic Group'), ('subcaste', 'Subcaste/Clan/Thang')], max_length=15)),
                ('historical_background', models.TextField(blank=True, help_text='Brief origin story of this demographic node.')),
                ('parent', models.ForeignKey(blank=True, help_text='For a Caste, select its dominant Religion. For a Subcaste, select its Caste.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sanskriti.ethnicityprofile')),
            ],
            options={
                'verbose_name': 'Demographic Profile',
                'verbose_name_plural': 'Demographic Profiles',
                'ordering': ['node_type', 'name'],
            },
        ),
    ]
